var slider = document.querySelector('.crypto_map_main')
var sl1 = document.querySelector('.slide_first')
var sl2 = document.querySelector('.slide_second')
var sl3 = document.querySelector('.slide_third')
var sl4 = document.querySelector('.slide_fourth')
var slide_first = document.querySelector('.crypto_map_number_slider_first')
var slide_second = document.querySelector('.crypto_map_number_slider_second')
var slide_third = document.querySelector('.crypto_map_number_slider_third')
var slide_fourth = document.querySelector('.crypto_map_number_slider_fourth')
var active = document.querySelector('.active')
slide_first.onclick = function(){
    slide_first.classList.add('active')
    slide_second.classList.remove('active')
    slide_third.classList.remove('active')
    slide_fourth.classList.remove('active')
    sl1.classList.add('fir')
    sl2.classList.add('fir')
    sl3.classList.add('fir')
    sl4.classList.add('fir')
    sl1.classList.remove('sec')
    sl2.classList.remove('sec')
    sl3.classList.remove('sec')
    sl4.classList.remove('sec')
    sl1.classList.remove('third')
    sl2.classList.remove('third')
    sl3.classList.remove('third')
    sl4.classList.remove('third')
    sl1.classList.remove('fourth')
    sl2.classList.remove('fourth')
    sl3.classList.remove('fourth')
    sl4.classList.remove('fourth')
}
slide_second.onclick = function(){
    slide_second.classList.add('active')
    slide_first.classList.remove('active')
    slide_third.classList.remove('active')
    slide_fourth.classList.remove('active')
    sl1.classList.remove('fir')
    sl2.classList.remove('fir')
    sl3.classList.remove('fir')
    sl4.classList.remove('fir')
    sl1.classList.add('sec')
    sl2.classList.add('sec')
    sl3.classList.add('sec')
    sl4.classList.add('sec')
    sl1.classList.remove('third')
    sl2.classList.remove('third')
    sl3.classList.remove('third')
    sl4.classList.remove('third')
    sl1.classList.remove('fourth')
    sl2.classList.remove('fourth')
    sl3.classList.remove('fourth')
    sl4.classList.remove('fourth')
}
slide_third.onclick = function(){
    slide_third.classList.add('active')
    slide_first.classList.remove('active')
    slide_second.classList.remove('active')
    slide_fourth.classList.remove('active')
    sl1.classList.remove('fir')
    sl2.classList.remove('fir')
    sl3.classList.remove('fir')
    sl4.classList.remove('fir')
    sl1.classList.remove('sec')
    sl2.classList.remove('sec')
    sl3.classList.remove('sec')
    sl4.classList.remove('sec')
    sl1.classList.add('third')
    sl2.classList.add('third')
    sl3.classList.add('third')
    sl4.classList.add('third')
    sl1.classList.remove('fourth')
    sl2.classList.remove('fourth')
    sl3.classList.remove('fourth')
    sl4.classList.remove('fourth')
}
slide_fourth.onclick = function(){
    slide_fourth.classList.add('active')
    slide_first.classList.remove('active')
    slide_second.classList.remove('active')
    slide_third.classList.remove('active')
    sl1.classList.remove('fir')
    sl2.classList.remove('fir')
    sl3.classList.remove('fir')
    sl4.classList.remove('fir')
    sl1.classList.remove('sec')
    sl2.classList.remove('sec')
    sl3.classList.remove('sec')
    sl4.classList.remove('sec')
    sl1.classList.remove('third')
    sl2.classList.remove('third')
    sl3.classList.remove('third')
    sl4.classList.remove('third')
    sl1.classList.add('fourth')
    sl2.classList.add('fourth')
    sl3.classList.add('fourth')
    sl4.classList.add('fourth')
}